config/routes.rb
Rails.application.routes.draw do
  resources :prompts

  get 'videos/new'

  get 'videos/all'

  get 'users/new'

  get 'users/edit'

  get 'users/show'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
belongs_to :user
before_save :check_sender
scope :recentvideos, order('created_at desc')
scope :unseen, where(seen_at: nil) 

	def check_sender
		if self.sender?
		self.sender = userid
		end	
	end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: [:show, :edit, :update, :destroy]

  # GET /prompts
  # GET /prompts.json
  def index
    @prompts = Prompt.all
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
  end

  # POST /prompts
  # POST /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to @prompt, notice: 'Prompt was successfully created.' }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :new }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1
  # PATCH/PUT /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to @prompt, notice: 'Prompt was successfully updated.' }
        format.json { render :show, status: :ok, location: @prompt }
      else
        format.html { render :edit }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1
  # DELETE /prompts/1.json
  def destroy
    @prompt.destroy
    respond_to do |format|
      format.html { redirect_to prompts_url, notice: 'Prompt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prompt_params
      params.require(:prompt).permit(:creator, :type, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	if params[:status] == "activated"
  		@users = User.activated
  	else
  		@users = User.inactivated
  	end
  end	

  def new
  end
  	
  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to @user
  	else
  		render "new"
  	end
  end

  def edit
  end

  def save
  	@user = User.save
  end

  def show
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
  	@video = Video.new
  end

  def all
  	@video = Video.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@videos = Video.all
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prompts/_form.html.erb
<%= form_for(@prompt) do |f| %>
  <% if @prompt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
      <% @prompt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creator %><br>
    <%= f.number_field :creator %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prompts/edit.html.erb
<h1>Editing prompt</h1>

<%= render 'form' %>

<%= link_to 'Show', @prompt %> |
<%= link_to 'Back', prompts_path %>

app/views/prompts/index.html.erb
<h1>Listing prompts</h1>

<table>
  <thead>
    <tr>
      <th>Creator</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prompts.each do |prompt| %>
      <tr>
        <td><%= prompt.creator %></td>
        <td><%= prompt.content %></td>
        <td><%= link_to 'Show', prompt %></td>
        <td><%= link_to 'Edit', edit_prompt_path(prompt) %></td>
        <td><%= link_to 'Destroy', prompt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prompt', new_prompt_path %>

app/views/prompts/new.html.erb
<h1>New prompt</h1>

<%= render 'form' %>

<%= link_to 'Back', prompts_path %>

app/views/prompts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creator:</strong>
  <%= @prompt.creator %>
</p>

<p>
  <strong>Content:</strong>
  <%= @prompt.content %>
</p>

<%= link_to 'Edit', edit_prompt_path(@prompt) %> |
<%= link_to 'Back', prompts_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/videos/all.html.erb
<h1>Videos#all</h1>
<p>Find me in app/views/videos/all.html.erb</p>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>The time is now: <%= Time.now %></p>